trigger:
- master

strategy:
  matrix:
    linux:
      vmImage: ubuntu-latest
    macOS:
      vmImage: macOS-latest
    windows:
      vmImage: windows-latest

pool:
  vmImage: $(vmImage)

steps:
  - template: ci/azure-install-rust.yml
    parameters:
      rust_version: stable

  - template: ci/azure-rustfmt.yml
    parameters:
      crate_path: .

  - template: ci/azure-runtests.yml
    parameters:
      crate_path: .

  - template: ci/azure_integration_test.yml
