trigger:
- master

strategy:
  matrix:
    linux:
      vmImage: ubuntu-16.04
    macOS:
      vmImage: macOS-10.13
    windows:
      vmImage: vs2017-win2016

pool:
  vmImage: $(vmImage)

steps:
  - template: ci/azure-install-rust.yml
    parameters:
      rust_version: stable

  - template: ci/azure-rustfmt.yml
    parameters:
      crate_path: .

  - template: ci/azure-runtests.yml
    parameters:
      crate_path: .

  - template: ci/azure-rustfmt.yml
    parameters:
      crate_path: diffr-lib

  - template: ci/azure-runtests.yml
    parameters:
      crate_path: diffr-lib
